### ISSUE TITLE
reaction_reaction_1 container exits after a few seconds

### ISSUE THREAD

**Issue by KostaStolbunsky** [reactioncommerce/reaction-development-platform#14]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
I cloned reaction-platform and ran the makefile as described.
All the networks and services have been created and started successfully. But reaction_reaction_1 container exits after few seconds.

_docker logs reaction_reaction_1_ command output:
up to date in 10.804s
MongoDB replica set initialized and ready.
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

**Comment by ticean** [comment]
Hi @KostaStolbunsky. Thanks for the report. The last line shows the problem:

`Error creating Reaction config file: /opt/reaction/src/.reaction/config.json`

That would be thrown by the [`reaction-cli`](https://github.com/reactioncommerce/reaction-cli/blob/v0.29.0/src/utils/config.js#L39-L102) that's used in the `reaction` project if there's an error writing a config file. This is a peculiar place to encounter an issue. Could it be a file permissions issue?

These questions might help narrow down the cause:

1. What is your host operating system?
2. How have you installed and configured Docker?
3. What version of Docker do you have installed?
3. What happens when you run an ephemeral container and try to modify the file system? Example `cd reaction && docker-compose run --rm reaction sh -c 'echo "user: $(whoami)\nhostname: $HOSTNAME" > .reaction/testfile'`.  This should write a new file in the `.reaction` directory with details from the container, so you can verify that the file was modified from within Docker. You should be able to see the files from your development host. `cat .reaction/testfile`.

**Comment by ticean** [comment]
> I solved the issue manually by coping this file from base Reaction installed locally on the host machine to Docker container
> `docker cp /home/user/reaction/src/.reaction/config.json reaction_reaction_1:/opt/reaction/src/.reaction/config.json`

@KostaStolbunsky oh ok, it sounds like you were running a Docker host remotely on DigitalOcean? It's still interesting that you would have a file issue like this. I'm glad that you got things working with a manual `docker cp`.

If you have insight on the DigitalOcean configuration that might have caused the issue then I'd love to hear. I think running in a remote context like this is a very interesting use case.

**Comment by KostaStolbunsky** [comment]
@ticean yes, I tried multiple times to install the platform on my Windows machine and in Virtualbox for Windows - no avail. That's the reason I'm using remote host as my Docker machine.

Anyway, I tried to deploy the platform one more time on DO droplet. This time I configured user to be able to run docker without sudo, set user's SSH key on Github, checked carefully permissions and ran make command. The result is same - 
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

**Comment by james-bucci** [comment]
@ticean  I'm having the same problem as @KostaStolbunsky.  

Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

I ran the test you suggested (cd reaction && docker-compose run --rm reaction sh -c 'echo "user: $(whoami)\nhostname: $HOSTNAME" > .reaction/testfile') and verified it does not have the correct permissions.

I'm not a Linux expert; can you please let me know how to resolve the permission issue?

Much appreciated!

**Comment by datamaker** [comment]
I am having the same problem.

```
gwonjeongbin-ui-iMac:reaction-platform dm$ docker ps
CONTAINER ID        IMAGE                             COMMAND                  CREATED              STATUS              PORTS                                                      NAMES
0e76b54e4d18        reaction_reaction                 "bash -c 'npm instal…"   About a minute ago   Up About a minute   0.0.0.0:3000->3000/tcp                                     reaction_reaction_1
bdb6c51317d8        reaction-next-starterkit_web      "/usr/local/src/reac…"   24 minutes ago       Up 9 minutes        0.0.0.0:4000->4000/tcp                                     reaction-next-starterkit_web_1
2d3c1fffcc1e        mongo:3.6.3                       "docker-entrypoint.s…"   27 minutes ago       Up 9 minutes        0.0.0.0:27017->27017/tcp                                   reaction_mongo_1
0fad23ff369b        oryd/hydra:v1.0.0-beta.9-alpine   "hydra serve all --d…"   31 minutes ago       Up 9 minutes        0.0.0.0:4444-4445->4444-4445/tcp, 0.0.0.0:5555->5555/tcp   reaction-hydra_hydra_1
0fca0d50cb59        postgres:10.3                     "docker-entrypoint.s…"   31 minutes ago       Up 9 minutes        0.0.0.0:32769->5432/tcp                                    reaction-hydra_postgres_1
gwonjeongbin-ui-iMac:reaction-platform dm$ docker logs 0e76b54e4d18
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 11.212s
MongoDB replica set initialized and ready.
Setting up plugin imports...

Setting up style imports...

Provisioning assets...

[[[[[ /opt/reaction/src ]]]]]

=> Started proxy.
=> Meteor 1.8 is available. Update this project with 'meteor update'.
gwonjeongbin-ui-iMac:reaction-platform dm$ docker logs 0e76b54e4d18
npm WARN react-addons-test-utils@15.6.2 requires a peer of react-dom@^15.4.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 11.212s
MongoDB replica set initialized and ready.
Setting up plugin imports...

Setting up style imports...

Provisioning assets...

[[[[[ /opt/reaction/src ]]]]]

=> Started proxy.
=> Meteor 1.8 is available. Update this project with 'meteor update'.
Killed
{ Error: Command failed: meteor --raw-logs
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at _callee$ (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:72:43)
    at tryCatch (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/reaction-cli/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:191)
    at /usr/local/lib/node_modules/reaction-cli/dist/commands/run.js:98:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  error: null,
  cmd: 'meteor --raw-logs',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
  options: 
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'meteor --raw-logs' ],
     envPairs: 
      [ 'TOOL_NODE_FLAGS=',
        'NODE_VERSION=8.11.3',
        'HOSTNAME=0e76b54e4d18',
        'METEOR_VERSION=1.7.0.3',
        'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
        'PWD=/opt/reaction/src',
        'MONGO_URL=mongodb://mongo:27017/reaction',
        'APP_BUNDLE_DIR=/opt/reaction/dist',
        'ROOT_URL=http://localhost:3000',
        'SHLVL=1',
        'HOME=/home/node',
        'YARN_VERSION=1.6.0',
        'REACTION_DOCKER_BUILD=true',
        'APP_SOURCE_DIR=/opt/reaction/src',
        'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
        'HYDRA_ADMIN_URL=http://hydra:4445',
        'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
        '_=/usr/local/bin/reaction' ],
     killSignal: undefined },
  envPairs: 
   [ 'TOOL_NODE_FLAGS=',
     'NODE_VERSION=8.11.3',
     'HOSTNAME=0e76b54e4d18',
     'METEOR_VERSION=1.7.0.3',
     'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor',
     'PWD=/opt/reaction/src',
     'MONGO_URL=mongodb://mongo:27017/reaction',
     'APP_BUNDLE_DIR=/opt/reaction/dist',
     'ROOT_URL=http://localhost:3000',
     'SHLVL=1',
     'HOME=/home/node',
     'YARN_VERSION=1.6.0',
     'REACTION_DOCKER_BUILD=true',
     'APP_SOURCE_DIR=/opt/reaction/src',
     'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
     'HYDRA_ADMIN_URL=http://hydra:4445',
     'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
     '_=/usr/local/bin/reaction' ],
  stderr: null,
  stdout: null,
  pid: 76,
  output: [ null, null, null ],
  signal: null,
  status: 137 }

Error: App failed to start
```

**Comment by chikondot** [comment]
@james-bucci @ticean 
I'm also having the exact same issue. was any solution found to the permissions issue?

Feedback would be much appreciated.

**Comment by dhcrzf** [comment]
Encountered this with a fresh install of ubuntu 18.04.1. The non-root user that was created during the ubuntu installation was able to run all of the reaction-platform services, but a second user following the same steps received the error - 

`Error creating Reaction config file: /opt/reaction/src/.reaction/config.json`

Followed by the reaction_reaction_1 container shutting down. Both users are members of the same groups in the OS.

**Comment by simplecommerce** [comment]
I have the same issue, tried uninstalling docker, docker-compose and ran the test mentioned above and do not have permission.

Also noticed that /opt/reaction path doesn't exist at all.

Any luck?

**Comment by james-bucci** [comment]
@ticean Hello Ticean, a few of us ( @simplecommerce @dhcrzf @chikondot) seem to be blocked by the same issue. Can you please help us resolve the config.json error?

**Comment by AaronZhangL** [comment]
----------OS: Fedora28------------------
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ uname -a
Linux localhost.localdomain 4.19.8-200.fc28.x86_64 #1 SMP Mon Dec 10 15:43:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ cat /etc/redhat-release
Fedora release 28 (Twenty Eight)
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ docker --version
Docker version 18.09.0, build 4d60db4
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ npm --version
6.4.1
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ node --version
v8.12.0
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ ls 
99_bakByAZ  CODE_OF_CONDUCT.md  config.mk  CONTRIBUTING.md  docs  LICENSE.md  Makefile  reaction  reaction-hydra  reaction-next-starterkit  README.md
Ξ (localhost.localdomain) 0_workspace/reaction-platform git:(master) $ git branch -a

* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
  remotes/origin/reaction-users


----------Issue----------------------------
Run [make] command under the [reaction-platform] folder, I got below errors:
===========
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json
npm WARN saveError EACCES: permission denied, open '/opt/reaction/src/package-lock.json.3285523079'
npm WARN react-taco-table@0.5.1 requires a peer of react@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN react-taco-table@0.5.1 requires a peer of react-dom@^15.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 31419 packages in 17.447s
found 8 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
MongoDB replica set initialized and ready.
Error creating Reaction config file: /opt/reaction/src/.reaction/config.json

**Comment by kodermax** [comment]
I have the same mistake.

**Comment by geourjoa** [comment]
Same problem on Ubuntu 18.10.

**Comment by j00p34** [comment]
Make sure your running make as the first user created on the system (UID 1000) 
Or change permissions on the directories created by make in the reaction-platform directory and ~/.cache/yarn-offline-mirror
Docker defaults to the first non-priviledged user. The make script is creating directories and mounting them on your docker containers. If you run make with another user it will create directories writable by you, not by the user the docker container is using.

**Comment by tarek369** [comment]
Where can i find config.json file to copy it inside docker  ?or how can i fix it, i want to install with docker on a vps

**Comment by brokenthorn** [comment]
I too am having the same problem with fresh minikube on MacOS Mojave via brew.

```sh
➜  reaction git:(cb6939db0) docker-compose run --rm reaction sh -c 'echo user: $(whoami) hostname: $HOSTNAME'
user: node hostname: 5ed4496f8a5b
```

No idea yet what to do next to fix this. The user with the problematic permissions seems to be 'node'.

**Comment by brokenthorn** [comment]
I did more digging and this is what I found.

```
➜  reaction git:(cb6939db0) docker-compose run --rm reaction ls -lha /opt
Starting reaction_mongo_1 ... done
total 16K
drwxr-xr-x 1 root root 4.0K Jan 14 11:18 .
drwxr-xr-x 1 root root 4.0K Feb 15 19:58 ..
drwxr-xr-x 1 root root 4.0K Jan 14 11:18 reaction
drwxr-xr-x 4 root root 4.0K Sep  5 10:20 yarn-v1.6.0
➜  reaction git:(cb6939db0) docker-compose run --rm reaction ls -lha /opt/reaction
Starting reaction_mongo_1 ... done
total 12K
drwxr-xr-x 1 root root 4.0K Jan 14 11:18 .
drwxr-xr-x 1 root root 4.0K Jan 14 11:18 ..
drwxr-xr-x 2 node root 4.0K Jan 14 11:17 dist
drwxr-xr-x 1 1001 1001 1.4K Feb 15 15:19 src
➜  reaction git:(cb6939db0) docker-compose run --rm reaction ls -lha /opt/reaction/src/.reaction
Starting reaction_mongo_1 ... done
total 8.0K
drwxr-xr-x 1 1001 1001  224 Feb 15 14:59 .
drwxr-xr-x 1 1001 1001 1.4K Feb 15 15:19 ..
drwxr-xr-x 1 1001 1001  128 Feb 15 14:59 ci
drwxr-xr-x 1 1001 1001  128 Feb 15 14:59 jsdoc
drwxr-xr-x 1 1001 1001  224 Feb 15 14:59 project-hooks
drwxr-xr-x 1 1001 1001  160 Feb 15 14:59 scripts
-rw-r--r-- 1 1001 1001 4.6K Feb 15 14:59 waitForMongo.js
```

Everything is traversable up to `/opt/reaction/src/.reaction` at the very least.
The problem though is that the current user (1000) has no permission to write anywhere - because everything is owned by 1001:1001 and doesn't set the write bit.

Container current user:

```
➜  reaction git:(cb6939db0) docker-compose run --rm reaction id     
Starting reaction_mongo_1 ... done
uid=1000(node) gid=1000(node) groups=1000(node)
```

I don't see user 1001 in the container though:

```
➜  reaction git:(cb6939db0) docker-compose run --rm reaction cat /etc/passwd 
Starting reaction_mongo_1 ... done
root:x:0:0:root:/root:/bin/bash
...
node:x:1000:1000::/home/node:/bin/bash
```

Does this mean that the permissions are wrong on the filesystem or that the 1001 user was supposed to be created but it didn't end up like that? I don't know how this stuff works though. I only know a few linux sys admin tricks.

**Comment by ticean** [comment]
This article, **"[Understanding how uid and gid work in Docker containers](https://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf)"**, offers a friendly explanation on how the user sharing in Docker is working between the container and the Docker host. I strongly recommend reading this to get a basic understanding of what's happening.

TLDR (but seriously read): 

**Users are shared between Docker container and the Linux host!**

#### The container's `node` user
The Reaction Dockerfile is [FROM](https://github.com/reactioncommerce/reaction/blob/master/Dockerfile#L4) the reactioncommerce/base image which is [FROM](https://github.com/reactioncommerce/base/blob/master/versions/meteor-1.8.0.2/Dockerfile#L1) the official [node](https://github.com/nodejs/docker-node/blob/86b9618674b01fc5549f83696a90d5bc21f38af0/8/stretch/Dockerfile#L3-L4) image on Docker Hub. _(Note: This is not the exact version, but they don't have git tags so I can't find it easily.)_

The `node` user is created with id `1000` in the official image with these lines:

```
RUN groupadd --gid 1000 node \
&& useradd --uid 1000 --gid node --shell /bin/bash --create-home node
```
As explained in the article the user ID of `1000` is the important part here. The username is just a convenient reference to this user.

#### Mapping the host user on Docker for Mac
All of this works out of the box when using Docker for Mac. osxfs pulls some tricks to make things work. It actually [tricks the container](https://docs.docker.com/docker-for-mac/osxfs/#ownership) to make it believe that it owns _everything_!

Docker for Mac automatically mounts the entire `Users` directory from the Mac into the Moby Linux VM.

#### Mapping the host user on Linux
None of this is handled for you on Linux, so you'll need to make sure there's a user on the host that corresponds to the user in the container.

On Linux, I think the options are to:

1. Create a user `1000` on the host machine and give it the appropriate permissions.
2. Start the Docker containers with another user. You can set the user by name or by ID in both Docker and Docker Compose. Specify this as any user on your machine that has access to the directories. The platform Docker Compose files don't have configuration for the user so I you'll need to manually edit them.

---

I'm on a Mac with Docker for Mac. I hope this information is helpful. But I haven't tested the above steps on a native Linux machine. We do have members of the team that run with the platform on Linux, though. 

@focusaurus reported #7 and it seems these are related. Though, I think the most flexible solution is to define users at container runtime, rather than at build time.

We'd be open to PR's to parameterize service users in the Docker Compose files so long as they have a default of `1000`. ENV can be used in Docker Compose files and are sourced from `.env`. Preferably such a solution would not require modification of many files.

**Comment by brokenthorn** [comment]
Wow, thank you! Would it be enough to add a comment in the Dockerfile about the need to run the container as the host machine user (ie. the dev) using docker-compose? Maybe if the makefile tasks could also automatically fix this by starting the containers under the current user? And maybe the getting starter for developers guide could also reflect some of this needed knowledge so developers coming to this platform don't get so discouraged from the beginning. Honestly, I thought this was a sign of the project's young age. Now let's go read that article you posted... 🤓

**Comment by brokenthorn** [comment]
I also found this [article](https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15) that talks about a possible solution using environment variables.

**Comment by aldeed** [comment]
Assuming this is fixed for everyone with the UID/GID fixing scripts we now have
