### ISSUE TITLE
Change ssh git url to https one

### ISSUE THREAD

**Issue by hamxabaig** [reactioncommerce/reaction-development-platform#78]
## Issue Description
When cloning the repo in a newly setup server, it requires you to have a properly setup github ssh key. Thats really annoying and i think the same can be done via using `https` urls of repos? It'll just make it easier to setup without additional steps

## Steps to Reproduce
Without having setup the ssh key to github, try running `make`. It'll error out. 

## Possible Solution
Replace `ssh` url of repos to `https`

**Comment by aldeed** [comment]
@ticean Any particular reason you went with SSH? They are all public so most likely https would work fine.

**Comment by ticean** [comment]
We're using SSH because it's a lot easier to configure authentication for private repositories. The canonical list of repos are public but its a common to have private ones in the mix.

If it's verified that we can have _both_ `git` and `https` in the list without problems then we could switch the public ones to `https` and document how to add private repos.

**Comment by delagroove** [comment]
Closing since the repos are listed as https
